import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="flex w-full   bg-white shadow-md  px-32 items-center justify-between  ">
          <a href="/">
            <Image
              onClick={() => console.log("clicked")}
              width={"220"}
              height={"50"}
              src={"/image.png"}
              className="pb-4"
            />{" "}
          </a>
          <div className="flex space-x-5 items-center m-4">
            <Link href="/#aboutus">
              <a className="hover:text-blue-500 hover:underline-offset-8 hover:underline">
                About us
              </a>
            </Link>
            <Link href={"/#howitworks"}>
              <a className="hover:text-blue-500 hover:underline-offset-8 hover:underline">
                How it works
              </a>
            </Link>
            <a href="/#consultation">
              <button className="bg-primary px-5 py-2 rounded text-white ">
                Get free consultation
              </button>
            </a>
          </div>
        </section>
        <section id="consultation" className=" flex  w-full">
          <div className=" w-3/5 flex flex-col  items-center pt-20">
            <div className="">
              <h1 className="text-3xl ">Digital Vastu Consultation</h1>
              <h1>Start your FREE digital consultation today!</h1>
            </div>

            <div className="bg-compass bg-[length:90%_90%] bg-no-repeat  w-2/3 bg-center">
              <form className="m-8 ">
                <div className="flex flex-col space-y-8 w-full justify-center">
                  <input
                    type="text"
                    placeholder="Name"
                    className="border w-full py-1.5 px-5 bg-transparent "
                  />
                  <input
                    type="number"
                    placeholder="Phone"
                    className="border w-full py-1.5 px-5 bg-transparent "
                  />
                  <input
                    type="email"
                    placeholder="Email"
                    className="border w-full py-1.5 px-5 bg-transparent "
                  />
                  <input
                    type="date"
                    placeholder="BirthDate"
                    className="border w-full py-1.5 px-5 bg-transparent "
                  />
                  <div className="flex space-x-5 w-full">
                    <input
                      type="text"
                      placeholder="Time of Birth"
                      className="border w-full py-1.5 px-5 bg-transparent "
                    />
                    <input
                      type="text"
                      placeholder="Place of Birth"
                      className="border w-full py-1.5 px-5 bg-transparent "
                    />
                  </div>
                  <div className="">
                    <button className="text-white bg-primary w-[150px] h-[50px] active:bg-secondary">
                      Submit
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </div>
          <div className=" w-2/5 bg-hero-banner bg-cover"></div>
        </section>
        <section
          id="aboutus"
          className="w-full flex flex-col items-center py-20 bg-slate-100"
        >
          <h1 className="text-3xl w-full text-center pb-5">What We Do</h1>
          <Image width={240} height={15} src={"/image2.png"} />
          <p className="w-1/2 text-center py-10">
            At Shikharvastu, we have team of experts who have successfully
            enriched lives through effective Vastu Home Planning and Numerology
            implementations.
          </p>
          <div className="flex justify-around  w-full px-32 ">
            <div className="pt-10 space-y-3 flex flex-col justify-center items-center">
              <Image width={80} height={80} src={"/Rectangle.png"} />
              <hr className="border-t border-blue-500 " />
              <h2>Digital Consultation</h2>
              <p className="w-2/3 text-sm text-center">
                Get a digital Vastu or Numerology consultation.
              </p>
            </div>
            <div className="pt-10 space-y-3 flex flex-col justify-center items-center">
              <Image width={80} height={80} src={"/Rectangle.png"} />
              <hr className="border-t border-blue-500 " />
              <h2>Digital Consultation</h2>
              <p className="w-2/3 text-sm text-center">
                Get a digital Vastu or Numerology consultation.
              </p>
            </div>
            <div className="pt-10 space-y-3 flex flex-col justify-center items-center">
              <Image width={80} height={80} src={"/Rectangle.png"} />
              <hr className="border-t border-blue-500 " />
              <h2>Digital Consultation</h2>
              <p className="w-2/3 text-sm text-center">
                Get a digital Vastu or Numerology consultation.
              </p>
            </div>
            <div className="pt-10 space-y-3 flex flex-col justify-center items-center">
              <Image width={80} height={80} src={"/Rectangle.png"} />
              <hr className="border-t border-blue-500 " />
              <h2>Digital Consultation</h2>
              <p className="w-2/3 text-sm text-center">
                Get a digital Vastu or Numerology consultation.
              </p>
            </div>
          </div>
        </section>
        <section>
          <div className="flex bg-white w-full   justify-around items-center m-10">
            <div className="flex-1 flex-col w-2/3 items-start pl-60  ">
              <Image width={150} height={150} src={"/image3.svg"} />
              <p className="text-start mb-4 pr-24">
                We are Partnered with Top Agents in your area to find the
                perfect Vastu home while providing you guidance and assistance
                in purchasing property for the right price under the best terms.
              </p>
              <a className="pt-20" href="">
                <button className="bg-primary px-5 py-2 rounded text-white">
                  Let's connect
                </button>
              </a>
            </div>
            <div className="flex-1 pr-60  ">
              <Image width={400} height={400} src={"/Rectangle2.png"} />
            </div>
          </div>
        </section>
        <section className="">
          <div className="flex  bg-slate-100 w-full   justify-between pb-20">
            <div className=" flex-1 items-center w-50vh  pl-40  pt-32">
              <Image width={500} height={300} src={"/Group.png"} />
            </div>
            <div className=" flex-1 fex-col  w-50vh pr-40 pl-40 pt-32  ">
              <Image width={120} height={50} src={"/image8.png"} />
              <p className=" text-start pt-20 pb-10 ">
                We are Partnered with Top Agents in your area to find the
                perfect Vastu home while providing you guidance and assistance
                in purchasing property for the right price under the best terms.
              </p>
              <a className="mb-10" href="">
                <button className="bg-primary px-5 py-2 rounded text-white">
                  Let's connect
                </button>
              </a>
            </div>
          </div>
        </section>
        <section id="howitworks" className="bg-white w-full p-24 pl-36 pr-36 ">
          <div className="flex-col bg-slate-50  items-center justify-center">
            <h1 className="text-center text-2xl pt-14">How it Works</h1>
            <h5 className="text-center">
              Get an expert with these 3 easy steps
            </h5>
            <div className="pt-20 items-center flex justify-center ">
              <Image width={800} height={200} src={"/Group2.png"} />
            </div>
            <div className="pb-20"></div>
          </div>
        </section>
        <section className="bg-white w-full flex flex-col justify-center items-center">
          <h1 className="text-3xl w-full text-center pb-5">What Client Says</h1>
          <Image width={240} height={15} src={"/image2.png"} />
          <p className="w-1/2 text-center py-10">
            Join the happy clients that use Vastu in their daily lives!
          </p>
          <div className="flex flex-row space-x-24 pb-36">
            <div>
              <Image width={200} height={200} src={"/Group26.png"} />
            </div>
            <div>
              <Image width={3} height={200} src={"/Line7.png"} />
            </div>
            <div>
              <Image width={600} height={200} src={"/Group4.png"} />
            </div>
          </div>
        </section>
        <section>
          <div className="bg-white p-20 w-full flex justify-center ">
            <div className="bg-slate-50 w-4/5  p-10 flex-col justify-center items-center">
              <h1 className="text-3xl text-center">Get a consultation</h1>
              <div className="flex flex-row py-20 space-x-16 px-20">
                <input
                  type="email"
                  placeholder="Your email address"
                  className="border w-full py-1.5 px-5 bg-transparent pr- drop-shadow-md hover:drop-shadow-xl"
                />
                <a href="">
                  <button className="bg-primary px-5 py-2  rounded text-white ">
                    Subscribe
                  </button>
                </a>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-secondary w-full h-96 flex flex-row justify-center items-center">
          <div className=" flex-1 flex-col flex justify-center items-start pl-32 ">
            <Image width={220} height={50} src={"/Logo4.png"} />
            <p className="text-white  pt-12">
              At Shikhar Vastu, we have team of experts who have successfully
              enriched lives through effective Vastu Home Planning and
              Numerology implementations.
            </p>
          </div>
          <div className=" flex-1 flex-col flex justify-center items-start pl-32">
            <h1 className="text-white text-3xl">Contact info</h1>
            <h1 className="text-white pt-16">hello@getvastu.com</h1>
            <h1 className="text-white pt-5">/getvastu</h1>
            <h1 className="text-white pt-5">@getvastu</h1>
          </div>
          <div className=" flex-1 flex-col flex justify-center items-start pl-32">
            <h1 className="text-white text-3xl">Sitemap</h1>
            <h1 className="text-white pt-16">Home</h1>
            <h1 className="text-white pt-5">About us</h1>
            <h1 className="text-white pt-5">How it works</h1>
          </div>
        </section>
      </main>
    </div>
  );
};

export default Home;
